version: '3.3'

services:
  jfrog:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    container_name: jfrog-artifactory
    ports:
      - 8081:8081
    volumes:
      - ./var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory